// Code generated by protoc-gen-go.
// source: dota_usermessages.proto
// DO NOT EDIT!

package dota2

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type EDotaUserMessages int32

const (
	EDotaUserMessages_DOTA_UM_AddUnitToSelection       EDotaUserMessages = 64
	EDotaUserMessages_DOTA_UM_AIDebugLine              EDotaUserMessages = 65
	EDotaUserMessages_DOTA_UM_ChatEvent                EDotaUserMessages = 66
	EDotaUserMessages_DOTA_UM_CombatHeroPositions      EDotaUserMessages = 67
	EDotaUserMessages_DOTA_UM_CombatLogData            EDotaUserMessages = 68
	EDotaUserMessages_DOTA_UM_CombatLogShowDeath       EDotaUserMessages = 70
	EDotaUserMessages_DOTA_UM_CreateLinearProjectile   EDotaUserMessages = 71
	EDotaUserMessages_DOTA_UM_DestroyLinearProjectile  EDotaUserMessages = 72
	EDotaUserMessages_DOTA_UM_DodgeTrackingProjectiles EDotaUserMessages = 73
	EDotaUserMessages_DOTA_UM_GlobalLightColor         EDotaUserMessages = 74
	EDotaUserMessages_DOTA_UM_GlobalLightDirection     EDotaUserMessages = 75
	EDotaUserMessages_DOTA_UM_InvalidCommand           EDotaUserMessages = 76
	EDotaUserMessages_DOTA_UM_LocationPing             EDotaUserMessages = 77
	EDotaUserMessages_DOTA_UM_MapLine                  EDotaUserMessages = 78
	EDotaUserMessages_DOTA_UM_MiniKillCamInfo          EDotaUserMessages = 79
	EDotaUserMessages_DOTA_UM_MinimapDebugPoint        EDotaUserMessages = 80
	EDotaUserMessages_DOTA_UM_MinimapEvent             EDotaUserMessages = 81
	EDotaUserMessages_DOTA_UM_NevermoreRequiem         EDotaUserMessages = 82
	EDotaUserMessages_DOTA_UM_OverheadEvent            EDotaUserMessages = 83
	EDotaUserMessages_DOTA_UM_SetNextAutobuyItem       EDotaUserMessages = 84
	EDotaUserMessages_DOTA_UM_SharedCooldown           EDotaUserMessages = 85
	EDotaUserMessages_DOTA_UM_SpectatorPlayerClick     EDotaUserMessages = 86
	EDotaUserMessages_DOTA_UM_TutorialTipInfo          EDotaUserMessages = 87
	EDotaUserMessages_DOTA_UM_UnitEvent                EDotaUserMessages = 88
	EDotaUserMessages_DOTA_UM_ParticleManager          EDotaUserMessages = 89
	EDotaUserMessages_DOTA_UM_BotChat                  EDotaUserMessages = 90
	EDotaUserMessages_DOTA_UM_HudError                 EDotaUserMessages = 91
	EDotaUserMessages_DOTA_UM_ItemPurchased            EDotaUserMessages = 92
	EDotaUserMessages_DOTA_UM_Ping                     EDotaUserMessages = 93
	EDotaUserMessages_DOTA_UM_ItemFound                EDotaUserMessages = 94
)

var EDotaUserMessages_name = map[int32]string{
	64: "DOTA_UM_AddUnitToSelection",
	65: "DOTA_UM_AIDebugLine",
	66: "DOTA_UM_ChatEvent",
	67: "DOTA_UM_CombatHeroPositions",
	68: "DOTA_UM_CombatLogData",
	70: "DOTA_UM_CombatLogShowDeath",
	71: "DOTA_UM_CreateLinearProjectile",
	72: "DOTA_UM_DestroyLinearProjectile",
	73: "DOTA_UM_DodgeTrackingProjectiles",
	74: "DOTA_UM_GlobalLightColor",
	75: "DOTA_UM_GlobalLightDirection",
	76: "DOTA_UM_InvalidCommand",
	77: "DOTA_UM_LocationPing",
	78: "DOTA_UM_MapLine",
	79: "DOTA_UM_MiniKillCamInfo",
	80: "DOTA_UM_MinimapDebugPoint",
	81: "DOTA_UM_MinimapEvent",
	82: "DOTA_UM_NevermoreRequiem",
	83: "DOTA_UM_OverheadEvent",
	84: "DOTA_UM_SetNextAutobuyItem",
	85: "DOTA_UM_SharedCooldown",
	86: "DOTA_UM_SpectatorPlayerClick",
	87: "DOTA_UM_TutorialTipInfo",
	88: "DOTA_UM_UnitEvent",
	89: "DOTA_UM_ParticleManager",
	90: "DOTA_UM_BotChat",
	91: "DOTA_UM_HudError",
	92: "DOTA_UM_ItemPurchased",
	93: "DOTA_UM_Ping",
	94: "DOTA_UM_ItemFound",
}
var EDotaUserMessages_value = map[string]int32{
	"DOTA_UM_AddUnitToSelection":       64,
	"DOTA_UM_AIDebugLine":              65,
	"DOTA_UM_ChatEvent":                66,
	"DOTA_UM_CombatHeroPositions":      67,
	"DOTA_UM_CombatLogData":            68,
	"DOTA_UM_CombatLogShowDeath":       70,
	"DOTA_UM_CreateLinearProjectile":   71,
	"DOTA_UM_DestroyLinearProjectile":  72,
	"DOTA_UM_DodgeTrackingProjectiles": 73,
	"DOTA_UM_GlobalLightColor":         74,
	"DOTA_UM_GlobalLightDirection":     75,
	"DOTA_UM_InvalidCommand":           76,
	"DOTA_UM_LocationPing":             77,
	"DOTA_UM_MapLine":                  78,
	"DOTA_UM_MiniKillCamInfo":          79,
	"DOTA_UM_MinimapDebugPoint":        80,
	"DOTA_UM_MinimapEvent":             81,
	"DOTA_UM_NevermoreRequiem":         82,
	"DOTA_UM_OverheadEvent":            83,
	"DOTA_UM_SetNextAutobuyItem":       84,
	"DOTA_UM_SharedCooldown":           85,
	"DOTA_UM_SpectatorPlayerClick":     86,
	"DOTA_UM_TutorialTipInfo":          87,
	"DOTA_UM_UnitEvent":                88,
	"DOTA_UM_ParticleManager":          89,
	"DOTA_UM_BotChat":                  90,
	"DOTA_UM_HudError":                 91,
	"DOTA_UM_ItemPurchased":            92,
	"DOTA_UM_Ping":                     93,
	"DOTA_UM_ItemFound":                94,
}

func (x EDotaUserMessages) Enum() *EDotaUserMessages {
	p := new(EDotaUserMessages)
	*p = x
	return p
}
func (x EDotaUserMessages) String() string {
	return proto.EnumName(EDotaUserMessages_name, int32(x))
}
func (x EDotaUserMessages) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *EDotaUserMessages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDotaUserMessages_value, data, "EDotaUserMessages")
	if err != nil {
		return err
	}
	*x = EDotaUserMessages(value)
	return nil
}

type DOTA_CHAT_MESSAGE int32

const (
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_INVALID                          DOTA_CHAT_MESSAGE = -1
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_HERO_KILL                        DOTA_CHAT_MESSAGE = 0
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_HERO_DENY                        DOTA_CHAT_MESSAGE = 1
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_BARRACKS_KILL                    DOTA_CHAT_MESSAGE = 2
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_TOWER_KILL                       DOTA_CHAT_MESSAGE = 3
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_TOWER_DENY                       DOTA_CHAT_MESSAGE = 4
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_FIRSTBLOOD                       DOTA_CHAT_MESSAGE = 5
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_STREAK_KILL                      DOTA_CHAT_MESSAGE = 6
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_BUYBACK                          DOTA_CHAT_MESSAGE = 7
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_AEGIS                            DOTA_CHAT_MESSAGE = 8
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ROSHAN_KILL                      DOTA_CHAT_MESSAGE = 9
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_COURIER_LOST                     DOTA_CHAT_MESSAGE = 10
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_COURIER_RESPAWNED                DOTA_CHAT_MESSAGE = 11
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_GLYPH_USED                       DOTA_CHAT_MESSAGE = 12
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ITEM_PURCHASE                    DOTA_CHAT_MESSAGE = 13
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CONNECT                          DOTA_CHAT_MESSAGE = 14
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_DISCONNECT                       DOTA_CHAT_MESSAGE = 15
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_DISCONNECT_WAIT_FOR_RECONNECT    DOTA_CHAT_MESSAGE = 16
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_DISCONNECT_TIME_REMAINING        DOTA_CHAT_MESSAGE = 17
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_DISCONNECT_TIME_REMAINING_PLURAL DOTA_CHAT_MESSAGE = 18
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_RECONNECT                        DOTA_CHAT_MESSAGE = 19
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ABANDON                          DOTA_CHAT_MESSAGE = 20
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_SAFE_TO_LEAVE                    DOTA_CHAT_MESSAGE = 21
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_RUNE_PICKUP                      DOTA_CHAT_MESSAGE = 22
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_RUNE_BOTTLE                      DOTA_CHAT_MESSAGE = 23
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_INTHEBAG                         DOTA_CHAT_MESSAGE = 24
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_SECRETSHOP                       DOTA_CHAT_MESSAGE = 25
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ITEM_AUTOPURCHASED               DOTA_CHAT_MESSAGE = 26
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ITEMS_COMBINED                   DOTA_CHAT_MESSAGE = 27
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_SUPER_CREEPS                     DOTA_CHAT_MESSAGE = 28
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CANT_USE_ACTION_ITEM             DOTA_CHAT_MESSAGE = 29
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CHARGES_EXHAUSTED                DOTA_CHAT_MESSAGE = 30
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CANTPAUSE                        DOTA_CHAT_MESSAGE = 31
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_NOPAUSESLEFT                     DOTA_CHAT_MESSAGE = 32
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CANTPAUSEYET                     DOTA_CHAT_MESSAGE = 33
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_PAUSED                           DOTA_CHAT_MESSAGE = 34
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_UNPAUSE_COUNTDOWN                DOTA_CHAT_MESSAGE = 35
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_UNPAUSED                         DOTA_CHAT_MESSAGE = 36
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_AUTO_UNPAUSED                    DOTA_CHAT_MESSAGE = 37
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_YOUPAUSED                        DOTA_CHAT_MESSAGE = 38
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_CANTUNPAUSETEAM                  DOTA_CHAT_MESSAGE = 39
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_SAFE_TO_LEAVE_ABANDONER          DOTA_CHAT_MESSAGE = 40
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_VOICE_TEXT_BANNED                DOTA_CHAT_MESSAGE = 41
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_SPECTATORS_WATCHING_THIS_GAME    DOTA_CHAT_MESSAGE = 42
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_REPORT_REMINDER                  DOTA_CHAT_MESSAGE = 43
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_ECON_ITEM                        DOTA_CHAT_MESSAGE = 44
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_TAUNT                            DOTA_CHAT_MESSAGE = 45
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_RANDOM                           DOTA_CHAT_MESSAGE = 46
	DOTA_CHAT_MESSAGE_CHAT_MESSAGE_RD_TURN                          DOTA_CHAT_MESSAGE = 47
)

var DOTA_CHAT_MESSAGE_name = map[int32]string{
	-1: "CHAT_MESSAGE_INVALID",
	0:  "CHAT_MESSAGE_HERO_KILL",
	1:  "CHAT_MESSAGE_HERO_DENY",
	2:  "CHAT_MESSAGE_BARRACKS_KILL",
	3:  "CHAT_MESSAGE_TOWER_KILL",
	4:  "CHAT_MESSAGE_TOWER_DENY",
	5:  "CHAT_MESSAGE_FIRSTBLOOD",
	6:  "CHAT_MESSAGE_STREAK_KILL",
	7:  "CHAT_MESSAGE_BUYBACK",
	8:  "CHAT_MESSAGE_AEGIS",
	9:  "CHAT_MESSAGE_ROSHAN_KILL",
	10: "CHAT_MESSAGE_COURIER_LOST",
	11: "CHAT_MESSAGE_COURIER_RESPAWNED",
	12: "CHAT_MESSAGE_GLYPH_USED",
	13: "CHAT_MESSAGE_ITEM_PURCHASE",
	14: "CHAT_MESSAGE_CONNECT",
	15: "CHAT_MESSAGE_DISCONNECT",
	16: "CHAT_MESSAGE_DISCONNECT_WAIT_FOR_RECONNECT",
	17: "CHAT_MESSAGE_DISCONNECT_TIME_REMAINING",
	18: "CHAT_MESSAGE_DISCONNECT_TIME_REMAINING_PLURAL",
	19: "CHAT_MESSAGE_RECONNECT",
	20: "CHAT_MESSAGE_ABANDON",
	21: "CHAT_MESSAGE_SAFE_TO_LEAVE",
	22: "CHAT_MESSAGE_RUNE_PICKUP",
	23: "CHAT_MESSAGE_RUNE_BOTTLE",
	24: "CHAT_MESSAGE_INTHEBAG",
	25: "CHAT_MESSAGE_SECRETSHOP",
	26: "CHAT_MESSAGE_ITEM_AUTOPURCHASED",
	27: "CHAT_MESSAGE_ITEMS_COMBINED",
	28: "CHAT_MESSAGE_SUPER_CREEPS",
	29: "CHAT_MESSAGE_CANT_USE_ACTION_ITEM",
	30: "CHAT_MESSAGE_CHARGES_EXHAUSTED",
	31: "CHAT_MESSAGE_CANTPAUSE",
	32: "CHAT_MESSAGE_NOPAUSESLEFT",
	33: "CHAT_MESSAGE_CANTPAUSEYET",
	34: "CHAT_MESSAGE_PAUSED",
	35: "CHAT_MESSAGE_UNPAUSE_COUNTDOWN",
	36: "CHAT_MESSAGE_UNPAUSED",
	37: "CHAT_MESSAGE_AUTO_UNPAUSED",
	38: "CHAT_MESSAGE_YOUPAUSED",
	39: "CHAT_MESSAGE_CANTUNPAUSETEAM",
	40: "CHAT_MESSAGE_SAFE_TO_LEAVE_ABANDONER",
	41: "CHAT_MESSAGE_VOICE_TEXT_BANNED",
	42: "CHAT_MESSAGE_SPECTATORS_WATCHING_THIS_GAME",
	43: "CHAT_MESSAGE_REPORT_REMINDER",
	44: "CHAT_MESSAGE_ECON_ITEM",
	45: "CHAT_MESSAGE_TAUNT",
	46: "CHAT_MESSAGE_RANDOM",
	47: "CHAT_MESSAGE_RD_TURN",
}
var DOTA_CHAT_MESSAGE_value = map[string]int32{
	"CHAT_MESSAGE_INVALID":                          -1,
	"CHAT_MESSAGE_HERO_KILL":                        0,
	"CHAT_MESSAGE_HERO_DENY":                        1,
	"CHAT_MESSAGE_BARRACKS_KILL":                    2,
	"CHAT_MESSAGE_TOWER_KILL":                       3,
	"CHAT_MESSAGE_TOWER_DENY":                       4,
	"CHAT_MESSAGE_FIRSTBLOOD":                       5,
	"CHAT_MESSAGE_STREAK_KILL":                      6,
	"CHAT_MESSAGE_BUYBACK":                          7,
	"CHAT_MESSAGE_AEGIS":                            8,
	"CHAT_MESSAGE_ROSHAN_KILL":                      9,
	"CHAT_MESSAGE_COURIER_LOST":                     10,
	"CHAT_MESSAGE_COURIER_RESPAWNED":                11,
	"CHAT_MESSAGE_GLYPH_USED":                       12,
	"CHAT_MESSAGE_ITEM_PURCHASE":                    13,
	"CHAT_MESSAGE_CONNECT":                          14,
	"CHAT_MESSAGE_DISCONNECT":                       15,
	"CHAT_MESSAGE_DISCONNECT_WAIT_FOR_RECONNECT":    16,
	"CHAT_MESSAGE_DISCONNECT_TIME_REMAINING":        17,
	"CHAT_MESSAGE_DISCONNECT_TIME_REMAINING_PLURAL": 18,
	"CHAT_MESSAGE_RECONNECT":                        19,
	"CHAT_MESSAGE_ABANDON":                          20,
	"CHAT_MESSAGE_SAFE_TO_LEAVE":                    21,
	"CHAT_MESSAGE_RUNE_PICKUP":                      22,
	"CHAT_MESSAGE_RUNE_BOTTLE":                      23,
	"CHAT_MESSAGE_INTHEBAG":                         24,
	"CHAT_MESSAGE_SECRETSHOP":                       25,
	"CHAT_MESSAGE_ITEM_AUTOPURCHASED":               26,
	"CHAT_MESSAGE_ITEMS_COMBINED":                   27,
	"CHAT_MESSAGE_SUPER_CREEPS":                     28,
	"CHAT_MESSAGE_CANT_USE_ACTION_ITEM":             29,
	"CHAT_MESSAGE_CHARGES_EXHAUSTED":                30,
	"CHAT_MESSAGE_CANTPAUSE":                        31,
	"CHAT_MESSAGE_NOPAUSESLEFT":                     32,
	"CHAT_MESSAGE_CANTPAUSEYET":                     33,
	"CHAT_MESSAGE_PAUSED":                           34,
	"CHAT_MESSAGE_UNPAUSE_COUNTDOWN":                35,
	"CHAT_MESSAGE_UNPAUSED":                         36,
	"CHAT_MESSAGE_AUTO_UNPAUSED":                    37,
	"CHAT_MESSAGE_YOUPAUSED":                        38,
	"CHAT_MESSAGE_CANTUNPAUSETEAM":                  39,
	"CHAT_MESSAGE_SAFE_TO_LEAVE_ABANDONER":          40,
	"CHAT_MESSAGE_VOICE_TEXT_BANNED":                41,
	"CHAT_MESSAGE_SPECTATORS_WATCHING_THIS_GAME":    42,
	"CHAT_MESSAGE_REPORT_REMINDER":                  43,
	"CHAT_MESSAGE_ECON_ITEM":                        44,
	"CHAT_MESSAGE_TAUNT":                            45,
	"CHAT_MESSAGE_RANDOM":                           46,
	"CHAT_MESSAGE_RD_TURN":                          47,
}

func (x DOTA_CHAT_MESSAGE) Enum() *DOTA_CHAT_MESSAGE {
	p := new(DOTA_CHAT_MESSAGE)
	*p = x
	return p
}
func (x DOTA_CHAT_MESSAGE) String() string {
	return proto.EnumName(DOTA_CHAT_MESSAGE_name, int32(x))
}
func (x DOTA_CHAT_MESSAGE) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DOTA_CHAT_MESSAGE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DOTA_CHAT_MESSAGE_value, data, "DOTA_CHAT_MESSAGE")
	if err != nil {
		return err
	}
	*x = DOTA_CHAT_MESSAGE(value)
	return nil
}

type EDotaEntityMessages int32

const (
	EDotaEntityMessages_DOTA_UNIT_SPEECH              EDotaEntityMessages = 0
	EDotaEntityMessages_DOTA_UNIT_SPEECH_MUTE         EDotaEntityMessages = 1
	EDotaEntityMessages_DOTA_UNIT_ADD_GESTURE         EDotaEntityMessages = 2
	EDotaEntityMessages_DOTA_UNIT_REMOVE_GESTURE      EDotaEntityMessages = 3
	EDotaEntityMessages_DOTA_UNIT_REMOVE_ALL_GESTURES EDotaEntityMessages = 4
	EDotaEntityMessages_DOTA_UNIT_FADE_GESTURE        EDotaEntityMessages = 6
)

var EDotaEntityMessages_name = map[int32]string{
	0: "DOTA_UNIT_SPEECH",
	1: "DOTA_UNIT_SPEECH_MUTE",
	2: "DOTA_UNIT_ADD_GESTURE",
	3: "DOTA_UNIT_REMOVE_GESTURE",
	4: "DOTA_UNIT_REMOVE_ALL_GESTURES",
	6: "DOTA_UNIT_FADE_GESTURE",
}
var EDotaEntityMessages_value = map[string]int32{
	"DOTA_UNIT_SPEECH":              0,
	"DOTA_UNIT_SPEECH_MUTE":         1,
	"DOTA_UNIT_ADD_GESTURE":         2,
	"DOTA_UNIT_REMOVE_GESTURE":      3,
	"DOTA_UNIT_REMOVE_ALL_GESTURES": 4,
	"DOTA_UNIT_FADE_GESTURE":        6,
}

func (x EDotaEntityMessages) Enum() *EDotaEntityMessages {
	p := new(EDotaEntityMessages)
	*p = x
	return p
}
func (x EDotaEntityMessages) String() string {
	return proto.EnumName(EDotaEntityMessages_name, int32(x))
}
func (x EDotaEntityMessages) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *EDotaEntityMessages) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EDotaEntityMessages_value, data, "EDotaEntityMessages")
	if err != nil {
		return err
	}
	*x = EDotaEntityMessages(value)
	return nil
}

type DOTA_PARTICLE_MESSAGE int32

const (
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_CREATE             DOTA_PARTICLE_MESSAGE = 0
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE             DOTA_PARTICLE_MESSAGE = 1
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FORWARD     DOTA_PARTICLE_MESSAGE = 2
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ORIENTATION DOTA_PARTICLE_MESSAGE = 3
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FALLBACK    DOTA_PARTICLE_MESSAGE = 4
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ENT         DOTA_PARTICLE_MESSAGE = 5
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_UPDATE_OFFSET      DOTA_PARTICLE_MESSAGE = 6
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_DESTROY            DOTA_PARTICLE_MESSAGE = 7
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_DESTROY_INVOLVING  DOTA_PARTICLE_MESSAGE = 8
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_RELEASE            DOTA_PARTICLE_MESSAGE = 9
	DOTA_PARTICLE_MESSAGE_DOTA_PARTICLE_MANAGER_EVENT_LATENCY            DOTA_PARTICLE_MESSAGE = 10
)

var DOTA_PARTICLE_MESSAGE_name = map[int32]string{
	0:  "DOTA_PARTICLE_MANAGER_EVENT_CREATE",
	1:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE",
	2:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FORWARD",
	3:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ORIENTATION",
	4:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FALLBACK",
	5:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ENT",
	6:  "DOTA_PARTICLE_MANAGER_EVENT_UPDATE_OFFSET",
	7:  "DOTA_PARTICLE_MANAGER_EVENT_DESTROY",
	8:  "DOTA_PARTICLE_MANAGER_EVENT_DESTROY_INVOLVING",
	9:  "DOTA_PARTICLE_MANAGER_EVENT_RELEASE",
	10: "DOTA_PARTICLE_MANAGER_EVENT_LATENCY",
}
var DOTA_PARTICLE_MESSAGE_value = map[string]int32{
	"DOTA_PARTICLE_MANAGER_EVENT_CREATE":             0,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE":             1,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FORWARD":     2,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ORIENTATION": 3,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE_FALLBACK":    4,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE_ENT":         5,
	"DOTA_PARTICLE_MANAGER_EVENT_UPDATE_OFFSET":      6,
	"DOTA_PARTICLE_MANAGER_EVENT_DESTROY":            7,
	"DOTA_PARTICLE_MANAGER_EVENT_DESTROY_INVOLVING":  8,
	"DOTA_PARTICLE_MANAGER_EVENT_RELEASE":            9,
	"DOTA_PARTICLE_MANAGER_EVENT_LATENCY":            10,
}

func (x DOTA_PARTICLE_MESSAGE) Enum() *DOTA_PARTICLE_MESSAGE {
	p := new(DOTA_PARTICLE_MESSAGE)
	*p = x
	return p
}
func (x DOTA_PARTICLE_MESSAGE) String() string {
	return proto.EnumName(DOTA_PARTICLE_MESSAGE_name, int32(x))
}
func (x DOTA_PARTICLE_MESSAGE) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DOTA_PARTICLE_MESSAGE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DOTA_PARTICLE_MESSAGE_value, data, "DOTA_PARTICLE_MESSAGE")
	if err != nil {
		return err
	}
	*x = DOTA_PARTICLE_MESSAGE(value)
	return nil
}

type DOTA_OVERHEAD_ALERT int32

const (
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_GOLD                DOTA_OVERHEAD_ALERT = 0
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_DENY                DOTA_OVERHEAD_ALERT = 1
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_CRITICAL            DOTA_OVERHEAD_ALERT = 2
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_XP                  DOTA_OVERHEAD_ALERT = 3
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_BONUS_SPELL_DAMAGE  DOTA_OVERHEAD_ALERT = 4
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_MISS                DOTA_OVERHEAD_ALERT = 5
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_DAMAGE              DOTA_OVERHEAD_ALERT = 6
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_EVADE               DOTA_OVERHEAD_ALERT = 7
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_BLOCK               DOTA_OVERHEAD_ALERT = 8
	DOTA_OVERHEAD_ALERT_OVERHEAD_ALERT_BONUS_POISON_DAMAGE DOTA_OVERHEAD_ALERT = 9
)

var DOTA_OVERHEAD_ALERT_name = map[int32]string{
	0: "OVERHEAD_ALERT_GOLD",
	1: "OVERHEAD_ALERT_DENY",
	2: "OVERHEAD_ALERT_CRITICAL",
	3: "OVERHEAD_ALERT_XP",
	4: "OVERHEAD_ALERT_BONUS_SPELL_DAMAGE",
	5: "OVERHEAD_ALERT_MISS",
	6: "OVERHEAD_ALERT_DAMAGE",
	7: "OVERHEAD_ALERT_EVADE",
	8: "OVERHEAD_ALERT_BLOCK",
	9: "OVERHEAD_ALERT_BONUS_POISON_DAMAGE",
}
var DOTA_OVERHEAD_ALERT_value = map[string]int32{
	"OVERHEAD_ALERT_GOLD":                0,
	"OVERHEAD_ALERT_DENY":                1,
	"OVERHEAD_ALERT_CRITICAL":            2,
	"OVERHEAD_ALERT_XP":                  3,
	"OVERHEAD_ALERT_BONUS_SPELL_DAMAGE":  4,
	"OVERHEAD_ALERT_MISS":                5,
	"OVERHEAD_ALERT_DAMAGE":              6,
	"OVERHEAD_ALERT_EVADE":               7,
	"OVERHEAD_ALERT_BLOCK":               8,
	"OVERHEAD_ALERT_BONUS_POISON_DAMAGE": 9,
}

func (x DOTA_OVERHEAD_ALERT) Enum() *DOTA_OVERHEAD_ALERT {
	p := new(DOTA_OVERHEAD_ALERT)
	*p = x
	return p
}
func (x DOTA_OVERHEAD_ALERT) String() string {
	return proto.EnumName(DOTA_OVERHEAD_ALERT_name, int32(x))
}
func (x DOTA_OVERHEAD_ALERT) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DOTA_OVERHEAD_ALERT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DOTA_OVERHEAD_ALERT_value, data, "DOTA_OVERHEAD_ALERT")
	if err != nil {
		return err
	}
	*x = DOTA_OVERHEAD_ALERT(value)
	return nil
}

type CDOTAUserMsg_AIDebugLine struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_AIDebugLine) Reset()         { *m = CDOTAUserMsg_AIDebugLine{} }
func (m *CDOTAUserMsg_AIDebugLine) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_AIDebugLine) ProtoMessage()    {}

func (m *CDOTAUserMsg_AIDebugLine) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CDOTAUserMsg_Ping struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_Ping) Reset()         { *m = CDOTAUserMsg_Ping{} }
func (m *CDOTAUserMsg_Ping) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_Ping) ProtoMessage()    {}

func (m *CDOTAUserMsg_Ping) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CDOTAUserMsg_ChatEvent struct {
	Type             *DOTA_CHAT_MESSAGE `protobuf:"varint,1,req,name=type,enum=dota2.DOTA_CHAT_MESSAGE" json:"type,omitempty"`
	Value            *uint32            `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Playerid_1       *int32             `protobuf:"zigzag32,3,opt,name=playerid_1,def=-1" json:"playerid_1,omitempty"`
	Playerid_2       *int32             `protobuf:"zigzag32,4,opt,name=playerid_2,def=-1" json:"playerid_2,omitempty"`
	Playerid_3       *int32             `protobuf:"zigzag32,5,opt,name=playerid_3,def=-1" json:"playerid_3,omitempty"`
	Playerid_4       *int32             `protobuf:"zigzag32,6,opt,name=playerid_4,def=-1" json:"playerid_4,omitempty"`
	Playerid_5       *int32             `protobuf:"zigzag32,7,opt,name=playerid_5,def=-1" json:"playerid_5,omitempty"`
	Playerid_6       *int32             `protobuf:"zigzag32,8,opt,name=playerid_6,def=-1" json:"playerid_6,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CDOTAUserMsg_ChatEvent) Reset()         { *m = CDOTAUserMsg_ChatEvent{} }
func (m *CDOTAUserMsg_ChatEvent) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_ChatEvent) ProtoMessage()    {}

const Default_CDOTAUserMsg_ChatEvent_Playerid_1 int32 = -1
const Default_CDOTAUserMsg_ChatEvent_Playerid_2 int32 = -1
const Default_CDOTAUserMsg_ChatEvent_Playerid_3 int32 = -1
const Default_CDOTAUserMsg_ChatEvent_Playerid_4 int32 = -1
const Default_CDOTAUserMsg_ChatEvent_Playerid_5 int32 = -1
const Default_CDOTAUserMsg_ChatEvent_Playerid_6 int32 = -1

func (m *CDOTAUserMsg_ChatEvent) GetType() DOTA_CHAT_MESSAGE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CDOTAUserMsg_ChatEvent) GetValue() uint32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_1() int32 {
	if m != nil && m.Playerid_1 != nil {
		return *m.Playerid_1
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_1
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_2() int32 {
	if m != nil && m.Playerid_2 != nil {
		return *m.Playerid_2
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_2
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_3() int32 {
	if m != nil && m.Playerid_3 != nil {
		return *m.Playerid_3
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_3
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_4() int32 {
	if m != nil && m.Playerid_4 != nil {
		return *m.Playerid_4
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_4
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_5() int32 {
	if m != nil && m.Playerid_5 != nil {
		return *m.Playerid_5
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_5
}

func (m *CDOTAUserMsg_ChatEvent) GetPlayerid_6() int32 {
	if m != nil && m.Playerid_6 != nil {
		return *m.Playerid_6
	}
	return Default_CDOTAUserMsg_ChatEvent_Playerid_6
}

type CDOTAUserMsg_CombatLogData struct {
	Type             *uint32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	TargetName       *uint32  `protobuf:"varint,2,opt,name=target_name" json:"target_name,omitempty"`
	AttackerName     *uint32  `protobuf:"varint,3,opt,name=attacker_name" json:"attacker_name,omitempty"`
	AttackerIllusion *bool    `protobuf:"varint,4,opt,name=attacker_illusion" json:"attacker_illusion,omitempty"`
	TargetIllusion   *bool    `protobuf:"varint,5,opt,name=target_illusion" json:"target_illusion,omitempty"`
	InflictorName    *uint32  `protobuf:"varint,6,opt,name=inflictor_name" json:"inflictor_name,omitempty"`
	Value            *int32   `protobuf:"varint,7,opt,name=value" json:"value,omitempty"`
	Health           *int32   `protobuf:"varint,8,opt,name=health" json:"health,omitempty"`
	Time             *float32 `protobuf:"fixed32,9,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDOTAUserMsg_CombatLogData) Reset()         { *m = CDOTAUserMsg_CombatLogData{} }
func (m *CDOTAUserMsg_CombatLogData) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_CombatLogData) ProtoMessage()    {}

func (m *CDOTAUserMsg_CombatLogData) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetTargetName() uint32 {
	if m != nil && m.TargetName != nil {
		return *m.TargetName
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetAttackerName() uint32 {
	if m != nil && m.AttackerName != nil {
		return *m.AttackerName
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetAttackerIllusion() bool {
	if m != nil && m.AttackerIllusion != nil {
		return *m.AttackerIllusion
	}
	return false
}

func (m *CDOTAUserMsg_CombatLogData) GetTargetIllusion() bool {
	if m != nil && m.TargetIllusion != nil {
		return *m.TargetIllusion
	}
	return false
}

func (m *CDOTAUserMsg_CombatLogData) GetInflictorName() uint32 {
	if m != nil && m.InflictorName != nil {
		return *m.InflictorName
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetHealth() int32 {
	if m != nil && m.Health != nil {
		return *m.Health
	}
	return 0
}

func (m *CDOTAUserMsg_CombatLogData) GetTime() float32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type CDOTAUserMsg_CombatLogShowDeath struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_CombatLogShowDeath) Reset()         { *m = CDOTAUserMsg_CombatLogShowDeath{} }
func (m *CDOTAUserMsg_CombatLogShowDeath) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_CombatLogShowDeath) ProtoMessage()    {}

type CDOTAUserMsg_BotChat struct {
	PlayerId         *uint32 `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	Format           *string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Message          *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Target           *string `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_BotChat) Reset()         { *m = CDOTAUserMsg_BotChat{} }
func (m *CDOTAUserMsg_BotChat) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_BotChat) ProtoMessage()    {}

func (m *CDOTAUserMsg_BotChat) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *CDOTAUserMsg_BotChat) GetFormat() string {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return ""
}

func (m *CDOTAUserMsg_BotChat) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *CDOTAUserMsg_BotChat) GetTarget() string {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return ""
}

type CDOTAUserMsg_CombatHeroPositions struct {
	Index            *uint32       `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Time             *int32        `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	WorldPos         *CMsgVector2D `protobuf:"bytes,3,opt,name=world_pos" json:"world_pos,omitempty"`
	Health           *int32        `protobuf:"varint,4,opt,name=health" json:"health,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CDOTAUserMsg_CombatHeroPositions) Reset()         { *m = CDOTAUserMsg_CombatHeroPositions{} }
func (m *CDOTAUserMsg_CombatHeroPositions) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_CombatHeroPositions) ProtoMessage()    {}

func (m *CDOTAUserMsg_CombatHeroPositions) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CDOTAUserMsg_CombatHeroPositions) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *CDOTAUserMsg_CombatHeroPositions) GetWorldPos() *CMsgVector2D {
	if m != nil {
		return m.WorldPos
	}
	return nil
}

func (m *CDOTAUserMsg_CombatHeroPositions) GetHealth() int32 {
	if m != nil && m.Health != nil {
		return *m.Health
	}
	return 0
}

type CDOTAUserMsg_MiniKillCamInfo struct {
	Attackers        []*CDOTAUserMsg_MiniKillCamInfo_Attacker `protobuf:"bytes,1,rep,name=attackers" json:"attackers,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *CDOTAUserMsg_MiniKillCamInfo) Reset()         { *m = CDOTAUserMsg_MiniKillCamInfo{} }
func (m *CDOTAUserMsg_MiniKillCamInfo) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_MiniKillCamInfo) ProtoMessage()    {}

func (m *CDOTAUserMsg_MiniKillCamInfo) GetAttackers() []*CDOTAUserMsg_MiniKillCamInfo_Attacker {
	if m != nil {
		return m.Attackers
	}
	return nil
}

type CDOTAUserMsg_MiniKillCamInfo_Attacker struct {
	Attacker         *uint32                                          `protobuf:"varint,1,opt,name=attacker" json:"attacker,omitempty"`
	TotalDamage      *int32                                           `protobuf:"varint,2,opt,name=total_damage" json:"total_damage,omitempty"`
	Abilities        []*CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability `protobuf:"bytes,3,rep,name=abilities" json:"abilities,omitempty"`
	XXX_unrecognized []byte                                           `json:"-"`
}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker) Reset()         { *m = CDOTAUserMsg_MiniKillCamInfo_Attacker{} }
func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_MiniKillCamInfo_Attacker) ProtoMessage()    {}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker) GetAttacker() uint32 {
	if m != nil && m.Attacker != nil {
		return *m.Attacker
	}
	return 0
}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker) GetTotalDamage() int32 {
	if m != nil && m.TotalDamage != nil {
		return *m.TotalDamage
	}
	return 0
}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker) GetAbilities() []*CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability {
	if m != nil {
		return m.Abilities
	}
	return nil
}

type CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability struct {
	Ability          *uint32 `protobuf:"varint,1,opt,name=ability" json:"ability,omitempty"`
	Damage           *int32  `protobuf:"varint,2,opt,name=damage" json:"damage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability) Reset() {
	*m = CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability{}
}
func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability) ProtoMessage() {}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability) GetAbility() uint32 {
	if m != nil && m.Ability != nil {
		return *m.Ability
	}
	return 0
}

func (m *CDOTAUserMsg_MiniKillCamInfo_Attacker_Ability) GetDamage() int32 {
	if m != nil && m.Damage != nil {
		return *m.Damage
	}
	return 0
}

type CDOTAUserMsg_GlobalLightColor struct {
	Color            *uint32  `protobuf:"varint,1,opt,name=color" json:"color,omitempty"`
	Duration         *float32 `protobuf:"fixed32,2,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDOTAUserMsg_GlobalLightColor) Reset()         { *m = CDOTAUserMsg_GlobalLightColor{} }
func (m *CDOTAUserMsg_GlobalLightColor) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_GlobalLightColor) ProtoMessage()    {}

func (m *CDOTAUserMsg_GlobalLightColor) GetColor() uint32 {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return 0
}

func (m *CDOTAUserMsg_GlobalLightColor) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CDOTAUserMsg_GlobalLightDirection struct {
	Direction        *CMsgVector `protobuf:"bytes,1,opt,name=direction" json:"direction,omitempty"`
	Duration         *float32    `protobuf:"fixed32,2,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_GlobalLightDirection) Reset()         { *m = CDOTAUserMsg_GlobalLightDirection{} }
func (m *CDOTAUserMsg_GlobalLightDirection) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_GlobalLightDirection) ProtoMessage()    {}

func (m *CDOTAUserMsg_GlobalLightDirection) GetDirection() *CMsgVector {
	if m != nil {
		return m.Direction
	}
	return nil
}

func (m *CDOTAUserMsg_GlobalLightDirection) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CDOTAUserMsg_LocationPing struct {
	PlayerId         *uint32                `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	LocationPing     *CDOTAMsg_LocationPing `protobuf:"bytes,2,opt,name=location_ping" json:"location_ping,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *CDOTAUserMsg_LocationPing) Reset()         { *m = CDOTAUserMsg_LocationPing{} }
func (m *CDOTAUserMsg_LocationPing) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_LocationPing) ProtoMessage()    {}

func (m *CDOTAUserMsg_LocationPing) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *CDOTAUserMsg_LocationPing) GetLocationPing() *CDOTAMsg_LocationPing {
	if m != nil {
		return m.LocationPing
	}
	return nil
}

type CDOTAUserMsg_MinimapEvent struct {
	EventType        *int32 `protobuf:"varint,1,opt,name=event_type" json:"event_type,omitempty"`
	EntityHandle     *int32 `protobuf:"varint,2,opt,name=entity_handle" json:"entity_handle,omitempty"`
	X                *int32 `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	Duration         *int32 `protobuf:"varint,5,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_MinimapEvent) Reset()         { *m = CDOTAUserMsg_MinimapEvent{} }
func (m *CDOTAUserMsg_MinimapEvent) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_MinimapEvent) ProtoMessage()    {}

func (m *CDOTAUserMsg_MinimapEvent) GetEventType() int32 {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapEvent) GetEntityHandle() int32 {
	if m != nil && m.EntityHandle != nil {
		return *m.EntityHandle
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapEvent) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapEvent) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapEvent) GetDuration() int32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CDOTAUserMsg_MapLine struct {
	PlayerId         *int32            `protobuf:"varint,1,opt,name=player_id" json:"player_id,omitempty"`
	Mapline          *CDOTAMsg_MapLine `protobuf:"bytes,2,opt,name=mapline" json:"mapline,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CDOTAUserMsg_MapLine) Reset()         { *m = CDOTAUserMsg_MapLine{} }
func (m *CDOTAUserMsg_MapLine) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_MapLine) ProtoMessage()    {}

func (m *CDOTAUserMsg_MapLine) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *CDOTAUserMsg_MapLine) GetMapline() *CDOTAMsg_MapLine {
	if m != nil {
		return m.Mapline
	}
	return nil
}

type CDOTAUserMsg_MinimapDebugPoint struct {
	Location         *CMsgVector `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Color            *uint32     `protobuf:"varint,2,opt,name=color" json:"color,omitempty"`
	Size             *int32      `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Duration         *float32    `protobuf:"fixed32,4,opt,name=duration" json:"duration,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_MinimapDebugPoint) Reset()         { *m = CDOTAUserMsg_MinimapDebugPoint{} }
func (m *CDOTAUserMsg_MinimapDebugPoint) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_MinimapDebugPoint) ProtoMessage()    {}

func (m *CDOTAUserMsg_MinimapDebugPoint) GetLocation() *CMsgVector {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *CDOTAUserMsg_MinimapDebugPoint) GetColor() uint32 {
	if m != nil && m.Color != nil {
		return *m.Color
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapDebugPoint) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *CDOTAUserMsg_MinimapDebugPoint) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

type CDOTAUserMsg_CreateLinearProjectile struct {
	Origin           *CMsgVector   `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Velocity         *CMsgVector2D `protobuf:"bytes,2,opt,name=velocity" json:"velocity,omitempty"`
	Latency          *int32        `protobuf:"varint,3,opt,name=latency" json:"latency,omitempty"`
	Entindex         *int32        `protobuf:"varint,4,opt,name=entindex" json:"entindex,omitempty"`
	ParticleIndex    *int32        `protobuf:"varint,5,opt,name=particle_index" json:"particle_index,omitempty"`
	Handle           *int32        `protobuf:"varint,6,opt,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CDOTAUserMsg_CreateLinearProjectile) Reset()         { *m = CDOTAUserMsg_CreateLinearProjectile{} }
func (m *CDOTAUserMsg_CreateLinearProjectile) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_CreateLinearProjectile) ProtoMessage()    {}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetOrigin() *CMsgVector {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetVelocity() *CMsgVector2D {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetLatency() int32 {
	if m != nil && m.Latency != nil {
		return *m.Latency
	}
	return 0
}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetEntindex() int32 {
	if m != nil && m.Entindex != nil {
		return *m.Entindex
	}
	return 0
}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetParticleIndex() int32 {
	if m != nil && m.ParticleIndex != nil {
		return *m.ParticleIndex
	}
	return 0
}

func (m *CDOTAUserMsg_CreateLinearProjectile) GetHandle() int32 {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return 0
}

type CDOTAUserMsg_DestroyLinearProjectile struct {
	Handle           *int32 `protobuf:"varint,1,opt,name=handle" json:"handle,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_DestroyLinearProjectile) Reset()         { *m = CDOTAUserMsg_DestroyLinearProjectile{} }
func (m *CDOTAUserMsg_DestroyLinearProjectile) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_DestroyLinearProjectile) ProtoMessage()    {}

func (m *CDOTAUserMsg_DestroyLinearProjectile) GetHandle() int32 {
	if m != nil && m.Handle != nil {
		return *m.Handle
	}
	return 0
}

type CDOTAUserMsg_DodgeTrackingProjectiles struct {
	Entindex         *int32 `protobuf:"varint,1,req,name=entindex" json:"entindex,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_DodgeTrackingProjectiles) Reset()         { *m = CDOTAUserMsg_DodgeTrackingProjectiles{} }
func (m *CDOTAUserMsg_DodgeTrackingProjectiles) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_DodgeTrackingProjectiles) ProtoMessage()    {}

func (m *CDOTAUserMsg_DodgeTrackingProjectiles) GetEntindex() int32 {
	if m != nil && m.Entindex != nil {
		return *m.Entindex
	}
	return 0
}

type CDOTAUserMsg_SpectatorPlayerClick struct {
	Entindex         *int32 `protobuf:"varint,1,req,name=entindex" json:"entindex,omitempty"`
	OrderType        *int32 `protobuf:"varint,2,opt,name=order_type" json:"order_type,omitempty"`
	TargetIndex      *int32 `protobuf:"varint,3,opt,name=target_index" json:"target_index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_SpectatorPlayerClick) Reset()         { *m = CDOTAUserMsg_SpectatorPlayerClick{} }
func (m *CDOTAUserMsg_SpectatorPlayerClick) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_SpectatorPlayerClick) ProtoMessage()    {}

func (m *CDOTAUserMsg_SpectatorPlayerClick) GetEntindex() int32 {
	if m != nil && m.Entindex != nil {
		return *m.Entindex
	}
	return 0
}

func (m *CDOTAUserMsg_SpectatorPlayerClick) GetOrderType() int32 {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return 0
}

func (m *CDOTAUserMsg_SpectatorPlayerClick) GetTargetIndex() int32 {
	if m != nil && m.TargetIndex != nil {
		return *m.TargetIndex
	}
	return 0
}

type CDOTAUserMsg_NevermoreRequiem struct {
	EntityHandle     *int32      `protobuf:"varint,1,opt,name=entity_handle" json:"entity_handle,omitempty"`
	Lines            *int32      `protobuf:"varint,2,opt,name=lines" json:"lines,omitempty"`
	Origin           *CMsgVector `protobuf:"bytes,3,opt,name=origin" json:"origin,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_NevermoreRequiem) Reset()         { *m = CDOTAUserMsg_NevermoreRequiem{} }
func (m *CDOTAUserMsg_NevermoreRequiem) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_NevermoreRequiem) ProtoMessage()    {}

func (m *CDOTAUserMsg_NevermoreRequiem) GetEntityHandle() int32 {
	if m != nil && m.EntityHandle != nil {
		return *m.EntityHandle
	}
	return 0
}

func (m *CDOTAUserMsg_NevermoreRequiem) GetLines() int32 {
	if m != nil && m.Lines != nil {
		return *m.Lines
	}
	return 0
}

func (m *CDOTAUserMsg_NevermoreRequiem) GetOrigin() *CMsgVector {
	if m != nil {
		return m.Origin
	}
	return nil
}

type CDOTAUserMsg_InvalidCommand struct {
	Message          *string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_InvalidCommand) Reset()         { *m = CDOTAUserMsg_InvalidCommand{} }
func (m *CDOTAUserMsg_InvalidCommand) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_InvalidCommand) ProtoMessage()    {}

func (m *CDOTAUserMsg_InvalidCommand) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type CDOTAUserMsg_HudError struct {
	OrderId          *int32 `protobuf:"varint,1,opt,name=order_id" json:"order_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_HudError) Reset()         { *m = CDOTAUserMsg_HudError{} }
func (m *CDOTAUserMsg_HudError) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_HudError) ProtoMessage()    {}

func (m *CDOTAUserMsg_HudError) GetOrderId() int32 {
	if m != nil && m.OrderId != nil {
		return *m.OrderId
	}
	return 0
}

type CDOTAUserMsg_SharedCooldown struct {
	Entindex         *int32   `protobuf:"varint,1,opt,name=entindex" json:"entindex,omitempty"`
	Name             *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Cooldown         *float32 `protobuf:"fixed32,3,opt,name=cooldown" json:"cooldown,omitempty"`
	NameIndex        *int32   `protobuf:"varint,4,opt,name=name_index" json:"name_index,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDOTAUserMsg_SharedCooldown) Reset()         { *m = CDOTAUserMsg_SharedCooldown{} }
func (m *CDOTAUserMsg_SharedCooldown) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_SharedCooldown) ProtoMessage()    {}

func (m *CDOTAUserMsg_SharedCooldown) GetEntindex() int32 {
	if m != nil && m.Entindex != nil {
		return *m.Entindex
	}
	return 0
}

func (m *CDOTAUserMsg_SharedCooldown) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CDOTAUserMsg_SharedCooldown) GetCooldown() float32 {
	if m != nil && m.Cooldown != nil {
		return *m.Cooldown
	}
	return 0
}

func (m *CDOTAUserMsg_SharedCooldown) GetNameIndex() int32 {
	if m != nil && m.NameIndex != nil {
		return *m.NameIndex
	}
	return 0
}

type CDOTAUserMsg_SetNextAutobuyItem struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_SetNextAutobuyItem) Reset()         { *m = CDOTAUserMsg_SetNextAutobuyItem{} }
func (m *CDOTAUserMsg_SetNextAutobuyItem) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_SetNextAutobuyItem) ProtoMessage()    {}

func (m *CDOTAUserMsg_SetNextAutobuyItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type CDOTAUserMsg_UnitEvent struct {
	MsgType          *EDotaEntityMessages                  `protobuf:"varint,1,req,name=msg_type,enum=dota2.EDotaEntityMessages" json:"msg_type,omitempty"`
	EntityIndex      *int32                                `protobuf:"varint,2,req,name=entity_index" json:"entity_index,omitempty"`
	Speech           *CDOTAUserMsg_UnitEvent_Speech        `protobuf:"bytes,3,opt,name=speech" json:"speech,omitempty"`
	SpeechMute       *CDOTAUserMsg_UnitEvent_SpeechMute    `protobuf:"bytes,4,opt,name=speech_mute" json:"speech_mute,omitempty"`
	AddGesture       *CDOTAUserMsg_UnitEvent_AddGesture    `protobuf:"bytes,5,opt,name=add_gesture" json:"add_gesture,omitempty"`
	RemoveGesture    *CDOTAUserMsg_UnitEvent_RemoveGesture `protobuf:"bytes,6,opt,name=remove_gesture" json:"remove_gesture,omitempty"`
	BloodImpact      *CDOTAUserMsg_UnitEvent_BloodImpact   `protobuf:"bytes,7,opt,name=blood_impact" json:"blood_impact,omitempty"`
	FadeGesture      *CDOTAUserMsg_UnitEvent_FadeGesture   `protobuf:"bytes,8,opt,name=fade_gesture" json:"fade_gesture,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent) Reset()         { *m = CDOTAUserMsg_UnitEvent{} }
func (m *CDOTAUserMsg_UnitEvent) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent) ProtoMessage()    {}

func (m *CDOTAUserMsg_UnitEvent) GetMsgType() EDotaEntityMessages {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent) GetEntityIndex() int32 {
	if m != nil && m.EntityIndex != nil {
		return *m.EntityIndex
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent) GetSpeech() *CDOTAUserMsg_UnitEvent_Speech {
	if m != nil {
		return m.Speech
	}
	return nil
}

func (m *CDOTAUserMsg_UnitEvent) GetSpeechMute() *CDOTAUserMsg_UnitEvent_SpeechMute {
	if m != nil {
		return m.SpeechMute
	}
	return nil
}

func (m *CDOTAUserMsg_UnitEvent) GetAddGesture() *CDOTAUserMsg_UnitEvent_AddGesture {
	if m != nil {
		return m.AddGesture
	}
	return nil
}

func (m *CDOTAUserMsg_UnitEvent) GetRemoveGesture() *CDOTAUserMsg_UnitEvent_RemoveGesture {
	if m != nil {
		return m.RemoveGesture
	}
	return nil
}

func (m *CDOTAUserMsg_UnitEvent) GetBloodImpact() *CDOTAUserMsg_UnitEvent_BloodImpact {
	if m != nil {
		return m.BloodImpact
	}
	return nil
}

func (m *CDOTAUserMsg_UnitEvent) GetFadeGesture() *CDOTAUserMsg_UnitEvent_FadeGesture {
	if m != nil {
		return m.FadeGesture
	}
	return nil
}

type CDOTAUserMsg_UnitEvent_Speech struct {
	Concept          *int32  `protobuf:"varint,1,opt,name=concept" json:"concept,omitempty"`
	Response         *string `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	RecipientType    *int32  `protobuf:"varint,3,opt,name=recipient_type" json:"recipient_type,omitempty"`
	Level            *int32  `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_Speech) Reset()         { *m = CDOTAUserMsg_UnitEvent_Speech{} }
func (m *CDOTAUserMsg_UnitEvent_Speech) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_Speech) ProtoMessage()    {}

func (m *CDOTAUserMsg_UnitEvent_Speech) GetConcept() int32 {
	if m != nil && m.Concept != nil {
		return *m.Concept
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_Speech) GetResponse() string {
	if m != nil && m.Response != nil {
		return *m.Response
	}
	return ""
}

func (m *CDOTAUserMsg_UnitEvent_Speech) GetRecipientType() int32 {
	if m != nil && m.RecipientType != nil {
		return *m.RecipientType
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_Speech) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type CDOTAUserMsg_UnitEvent_SpeechMute struct {
	Delay            *float32 `protobuf:"fixed32,1,opt,name=delay,def=0.5" json:"delay,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_SpeechMute) Reset()         { *m = CDOTAUserMsg_UnitEvent_SpeechMute{} }
func (m *CDOTAUserMsg_UnitEvent_SpeechMute) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_SpeechMute) ProtoMessage()    {}

const Default_CDOTAUserMsg_UnitEvent_SpeechMute_Delay float32 = 0.5

func (m *CDOTAUserMsg_UnitEvent_SpeechMute) GetDelay() float32 {
	if m != nil && m.Delay != nil {
		return *m.Delay
	}
	return Default_CDOTAUserMsg_UnitEvent_SpeechMute_Delay
}

type CDOTAUserMsg_UnitEvent_AddGesture struct {
	Activity         *Activity `protobuf:"varint,1,opt,name=activity,enum=dota2.Activity" json:"activity,omitempty"`
	Slot             *int32    `protobuf:"varint,2,opt,name=slot" json:"slot,omitempty"`
	FadeIn           *float32  `protobuf:"fixed32,3,opt,name=fade_in,def=0" json:"fade_in,omitempty"`
	FadeOut          *float32  `protobuf:"fixed32,4,opt,name=fade_out,def=0.1" json:"fade_out,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_AddGesture) Reset()         { *m = CDOTAUserMsg_UnitEvent_AddGesture{} }
func (m *CDOTAUserMsg_UnitEvent_AddGesture) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_AddGesture) ProtoMessage()    {}

const Default_CDOTAUserMsg_UnitEvent_AddGesture_FadeIn float32 = 0
const Default_CDOTAUserMsg_UnitEvent_AddGesture_FadeOut float32 = 0.1

func (m *CDOTAUserMsg_UnitEvent_AddGesture) GetActivity() Activity {
	if m != nil && m.Activity != nil {
		return *m.Activity
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_AddGesture) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_AddGesture) GetFadeIn() float32 {
	if m != nil && m.FadeIn != nil {
		return *m.FadeIn
	}
	return Default_CDOTAUserMsg_UnitEvent_AddGesture_FadeIn
}

func (m *CDOTAUserMsg_UnitEvent_AddGesture) GetFadeOut() float32 {
	if m != nil && m.FadeOut != nil {
		return *m.FadeOut
	}
	return Default_CDOTAUserMsg_UnitEvent_AddGesture_FadeOut
}

type CDOTAUserMsg_UnitEvent_RemoveGesture struct {
	Activity         *Activity `protobuf:"varint,1,opt,name=activity,enum=dota2.Activity" json:"activity,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_RemoveGesture) Reset()         { *m = CDOTAUserMsg_UnitEvent_RemoveGesture{} }
func (m *CDOTAUserMsg_UnitEvent_RemoveGesture) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_RemoveGesture) ProtoMessage()    {}

func (m *CDOTAUserMsg_UnitEvent_RemoveGesture) GetActivity() Activity {
	if m != nil && m.Activity != nil {
		return *m.Activity
	}
	return 0
}

type CDOTAUserMsg_UnitEvent_BloodImpact struct {
	Scale            *int32 `protobuf:"varint,1,opt,name=scale" json:"scale,omitempty"`
	XNormal          *int32 `protobuf:"varint,2,opt,name=x_normal" json:"x_normal,omitempty"`
	YNormal          *int32 `protobuf:"varint,3,opt,name=y_normal" json:"y_normal,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_BloodImpact) Reset()         { *m = CDOTAUserMsg_UnitEvent_BloodImpact{} }
func (m *CDOTAUserMsg_UnitEvent_BloodImpact) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_BloodImpact) ProtoMessage()    {}

func (m *CDOTAUserMsg_UnitEvent_BloodImpact) GetScale() int32 {
	if m != nil && m.Scale != nil {
		return *m.Scale
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_BloodImpact) GetXNormal() int32 {
	if m != nil && m.XNormal != nil {
		return *m.XNormal
	}
	return 0
}

func (m *CDOTAUserMsg_UnitEvent_BloodImpact) GetYNormal() int32 {
	if m != nil && m.YNormal != nil {
		return *m.YNormal
	}
	return 0
}

type CDOTAUserMsg_UnitEvent_FadeGesture struct {
	Activity         *Activity `protobuf:"varint,1,opt,name=activity,enum=dota2.Activity" json:"activity,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CDOTAUserMsg_UnitEvent_FadeGesture) Reset()         { *m = CDOTAUserMsg_UnitEvent_FadeGesture{} }
func (m *CDOTAUserMsg_UnitEvent_FadeGesture) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_UnitEvent_FadeGesture) ProtoMessage()    {}

func (m *CDOTAUserMsg_UnitEvent_FadeGesture) GetActivity() Activity {
	if m != nil && m.Activity != nil {
		return *m.Activity
	}
	return 0
}

type CDOTAUserMsg_ItemPurchased struct {
	ItemIndex        *int32 `protobuf:"varint,1,opt,name=item_index" json:"item_index,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_ItemPurchased) Reset()         { *m = CDOTAUserMsg_ItemPurchased{} }
func (m *CDOTAUserMsg_ItemPurchased) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_ItemPurchased) ProtoMessage()    {}

func (m *CDOTAUserMsg_ItemPurchased) GetItemIndex() int32 {
	if m != nil && m.ItemIndex != nil {
		return *m.ItemIndex
	}
	return 0
}

type CDOTAUserMsg_ItemFound struct {
	Player           *int32 `protobuf:"varint,1,opt,name=player" json:"player,omitempty"`
	Quality          *int32 `protobuf:"varint,2,opt,name=quality" json:"quality,omitempty"`
	Rarity           *int32 `protobuf:"varint,3,opt,name=rarity" json:"rarity,omitempty"`
	Method           *int32 `protobuf:"varint,4,opt,name=method" json:"method,omitempty"`
	Itemdef          *int32 `protobuf:"varint,5,opt,name=itemdef" json:"itemdef,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_ItemFound) Reset()         { *m = CDOTAUserMsg_ItemFound{} }
func (m *CDOTAUserMsg_ItemFound) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_ItemFound) ProtoMessage()    {}

func (m *CDOTAUserMsg_ItemFound) GetPlayer() int32 {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return 0
}

func (m *CDOTAUserMsg_ItemFound) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

func (m *CDOTAUserMsg_ItemFound) GetRarity() int32 {
	if m != nil && m.Rarity != nil {
		return *m.Rarity
	}
	return 0
}

func (m *CDOTAUserMsg_ItemFound) GetMethod() int32 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *CDOTAUserMsg_ItemFound) GetItemdef() int32 {
	if m != nil && m.Itemdef != nil {
		return *m.Itemdef
	}
	return 0
}

type CDOTAUserMsg_ParticleManager struct {
	Type                     *DOTA_PARTICLE_MESSAGE                                 `protobuf:"varint,1,req,name=type,enum=dota2.DOTA_PARTICLE_MESSAGE" json:"type,omitempty"`
	Index                    *uint32                                                `protobuf:"varint,2,req,name=index" json:"index,omitempty"`
	ReleaseParticleIndex     *CDOTAUserMsg_ParticleManager_ReleaseParticleIndex     `protobuf:"bytes,3,opt,name=release_particle_index" json:"release_particle_index,omitempty"`
	CreateParticle           *CDOTAUserMsg_ParticleManager_CreateParticle           `protobuf:"bytes,4,opt,name=create_particle" json:"create_particle,omitempty"`
	DestroyParticle          *CDOTAUserMsg_ParticleManager_DestroyParticle          `protobuf:"bytes,5,opt,name=destroy_particle" json:"destroy_particle,omitempty"`
	DestroyParticleInvolving *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving `protobuf:"bytes,6,opt,name=destroy_particle_involving" json:"destroy_particle_involving,omitempty"`
	UpdateParticle           *CDOTAUserMsg_ParticleManager_UpdateParticle           `protobuf:"bytes,7,opt,name=update_particle" json:"update_particle,omitempty"`
	UpdateParticleFwd        *CDOTAUserMsg_ParticleManager_UpdateParticleFwd        `protobuf:"bytes,8,opt,name=update_particle_fwd" json:"update_particle_fwd,omitempty"`
	UpdateParticleOrient     *CDOTAUserMsg_ParticleManager_UpdateParticleOrient     `protobuf:"bytes,9,opt,name=update_particle_orient" json:"update_particle_orient,omitempty"`
	UpdateParticleFallback   *CDOTAUserMsg_ParticleManager_UpdateParticleFallback   `protobuf:"bytes,10,opt,name=update_particle_fallback" json:"update_particle_fallback,omitempty"`
	UpdateParticleOffset     *CDOTAUserMsg_ParticleManager_UpdateParticleOffset     `protobuf:"bytes,11,opt,name=update_particle_offset" json:"update_particle_offset,omitempty"`
	UpdateParticleEnt        *CDOTAUserMsg_ParticleManager_UpdateParticleEnt        `protobuf:"bytes,12,opt,name=update_particle_ent" json:"update_particle_ent,omitempty"`
	UpdateParticleLatency    *CDOTAUserMsg_ParticleManager_UpdateParticleLatency    `protobuf:"bytes,13,opt,name=update_particle_latency" json:"update_particle_latency,omitempty"`
	XXX_unrecognized         []byte                                                 `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager) Reset()         { *m = CDOTAUserMsg_ParticleManager{} }
func (m *CDOTAUserMsg_ParticleManager) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_ParticleManager) ProtoMessage()    {}

func (m *CDOTAUserMsg_ParticleManager) GetType() DOTA_PARTICLE_MESSAGE {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager) GetReleaseParticleIndex() *CDOTAUserMsg_ParticleManager_ReleaseParticleIndex {
	if m != nil {
		return m.ReleaseParticleIndex
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetCreateParticle() *CDOTAUserMsg_ParticleManager_CreateParticle {
	if m != nil {
		return m.CreateParticle
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetDestroyParticle() *CDOTAUserMsg_ParticleManager_DestroyParticle {
	if m != nil {
		return m.DestroyParticle
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetDestroyParticleInvolving() *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving {
	if m != nil {
		return m.DestroyParticleInvolving
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticle() *CDOTAUserMsg_ParticleManager_UpdateParticle {
	if m != nil {
		return m.UpdateParticle
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleFwd() *CDOTAUserMsg_ParticleManager_UpdateParticleFwd {
	if m != nil {
		return m.UpdateParticleFwd
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleOrient() *CDOTAUserMsg_ParticleManager_UpdateParticleOrient {
	if m != nil {
		return m.UpdateParticleOrient
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleFallback() *CDOTAUserMsg_ParticleManager_UpdateParticleFallback {
	if m != nil {
		return m.UpdateParticleFallback
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleOffset() *CDOTAUserMsg_ParticleManager_UpdateParticleOffset {
	if m != nil {
		return m.UpdateParticleOffset
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleEnt() *CDOTAUserMsg_ParticleManager_UpdateParticleEnt {
	if m != nil {
		return m.UpdateParticleEnt
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager) GetUpdateParticleLatency() *CDOTAUserMsg_ParticleManager_UpdateParticleLatency {
	if m != nil {
		return m.UpdateParticleLatency
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_ReleaseParticleIndex struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_ReleaseParticleIndex) Reset() {
	*m = CDOTAUserMsg_ParticleManager_ReleaseParticleIndex{}
}
func (m *CDOTAUserMsg_ParticleManager_ReleaseParticleIndex) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_ReleaseParticleIndex) ProtoMessage() {}

type CDOTAUserMsg_ParticleManager_CreateParticle struct {
	ParticleNameIndex *int32 `protobuf:"varint,1,opt,name=particle_name_index" json:"particle_name_index,omitempty"`
	AttachType        *int32 `protobuf:"varint,2,opt,name=attach_type" json:"attach_type,omitempty"`
	EntityHandle      *int32 `protobuf:"varint,3,opt,name=entity_handle" json:"entity_handle,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_CreateParticle) Reset() {
	*m = CDOTAUserMsg_ParticleManager_CreateParticle{}
}
func (m *CDOTAUserMsg_ParticleManager_CreateParticle) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_CreateParticle) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_CreateParticle) GetParticleNameIndex() int32 {
	if m != nil && m.ParticleNameIndex != nil {
		return *m.ParticleNameIndex
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_CreateParticle) GetAttachType() int32 {
	if m != nil && m.AttachType != nil {
		return *m.AttachType
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_CreateParticle) GetEntityHandle() int32 {
	if m != nil && m.EntityHandle != nil {
		return *m.EntityHandle
	}
	return 0
}

type CDOTAUserMsg_ParticleManager_DestroyParticle struct {
	DestroyImmediately *bool  `protobuf:"varint,1,opt,name=destroy_immediately" json:"destroy_immediately,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_DestroyParticle) Reset() {
	*m = CDOTAUserMsg_ParticleManager_DestroyParticle{}
}
func (m *CDOTAUserMsg_ParticleManager_DestroyParticle) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_DestroyParticle) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_DestroyParticle) GetDestroyImmediately() bool {
	if m != nil && m.DestroyImmediately != nil {
		return *m.DestroyImmediately
	}
	return false
}

type CDOTAUserMsg_ParticleManager_DestroyParticleInvolving struct {
	DestroyImmediately *bool  `protobuf:"varint,1,opt,name=destroy_immediately" json:"destroy_immediately,omitempty"`
	EntityHandle       *int32 `protobuf:"varint,3,opt,name=entity_handle" json:"entity_handle,omitempty"`
	XXX_unrecognized   []byte `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving) Reset() {
	*m = CDOTAUserMsg_ParticleManager_DestroyParticleInvolving{}
}
func (m *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_DestroyParticleInvolving) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving) GetDestroyImmediately() bool {
	if m != nil && m.DestroyImmediately != nil {
		return *m.DestroyImmediately
	}
	return false
}

func (m *CDOTAUserMsg_ParticleManager_DestroyParticleInvolving) GetEntityHandle() int32 {
	if m != nil && m.EntityHandle != nil {
		return *m.EntityHandle
	}
	return 0
}

type CDOTAUserMsg_ParticleManager_UpdateParticle struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	Position         *CMsgVector `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticle) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticle{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticle) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticle) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticle) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticle) GetPosition() *CMsgVector {
	if m != nil {
		return m.Position
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleFwd struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	Forward          *CMsgVector `protobuf:"bytes,2,opt,name=forward" json:"forward,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFwd) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleFwd{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFwd) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleFwd) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFwd) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFwd) GetForward() *CMsgVector {
	if m != nil {
		return m.Forward
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleOrient struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	Forward          *CMsgVector `protobuf:"bytes,2,opt,name=forward" json:"forward,omitempty"`
	Right            *CMsgVector `protobuf:"bytes,3,opt,name=right" json:"right,omitempty"`
	Up               *CMsgVector `protobuf:"bytes,4,opt,name=up" json:"up,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleOrient{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleOrient) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) GetForward() *CMsgVector {
	if m != nil {
		return m.Forward
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) GetRight() *CMsgVector {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOrient) GetUp() *CMsgVector {
	if m != nil {
		return m.Up
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleFallback struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	Position         *CMsgVector `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFallback) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleFallback{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFallback) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleFallback) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFallback) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleFallback) GetPosition() *CMsgVector {
	if m != nil {
		return m.Position
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleOffset struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	OriginOffset     *CMsgVector `protobuf:"bytes,2,opt,name=origin_offset" json:"origin_offset,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOffset) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleOffset{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOffset) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleOffset) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOffset) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleOffset) GetOriginOffset() *CMsgVector {
	if m != nil {
		return m.OriginOffset
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleEnt struct {
	ControlPoint     *int32      `protobuf:"varint,1,opt,name=control_point" json:"control_point,omitempty"`
	EntityHandle     *int32      `protobuf:"varint,2,opt,name=entity_handle" json:"entity_handle,omitempty"`
	AttachType       *int32      `protobuf:"varint,3,opt,name=attach_type" json:"attach_type,omitempty"`
	Attachment       *int32      `protobuf:"varint,4,opt,name=attachment" json:"attachment,omitempty"`
	FallbackPosition *CMsgVector `protobuf:"bytes,5,opt,name=fallback_position" json:"fallback_position,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleEnt{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleEnt) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) GetControlPoint() int32 {
	if m != nil && m.ControlPoint != nil {
		return *m.ControlPoint
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) GetEntityHandle() int32 {
	if m != nil && m.EntityHandle != nil {
		return *m.EntityHandle
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) GetAttachType() int32 {
	if m != nil && m.AttachType != nil {
		return *m.AttachType
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) GetAttachment() int32 {
	if m != nil && m.Attachment != nil {
		return *m.Attachment
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleEnt) GetFallbackPosition() *CMsgVector {
	if m != nil {
		return m.FallbackPosition
	}
	return nil
}

type CDOTAUserMsg_ParticleManager_UpdateParticleLatency struct {
	PlayerLatency    *int32 `protobuf:"varint,1,opt,name=player_latency" json:"player_latency,omitempty"`
	Tick             *int32 `protobuf:"varint,2,opt,name=tick" json:"tick,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleLatency) Reset() {
	*m = CDOTAUserMsg_ParticleManager_UpdateParticleLatency{}
}
func (m *CDOTAUserMsg_ParticleManager_UpdateParticleLatency) String() string {
	return proto.CompactTextString(m)
}
func (*CDOTAUserMsg_ParticleManager_UpdateParticleLatency) ProtoMessage() {}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleLatency) GetPlayerLatency() int32 {
	if m != nil && m.PlayerLatency != nil {
		return *m.PlayerLatency
	}
	return 0
}

func (m *CDOTAUserMsg_ParticleManager_UpdateParticleLatency) GetTick() int32 {
	if m != nil && m.Tick != nil {
		return *m.Tick
	}
	return 0
}

type CDOTAUserMsg_OverheadEvent struct {
	MessageType          *DOTA_OVERHEAD_ALERT `protobuf:"varint,1,req,name=message_type,enum=dota2.DOTA_OVERHEAD_ALERT" json:"message_type,omitempty"`
	Value                *int32               `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	TargetPlayerEntindex *int32               `protobuf:"varint,3,opt,name=target_player_entindex" json:"target_player_entindex,omitempty"`
	TargetEntindex       *int32               `protobuf:"varint,4,opt,name=target_entindex" json:"target_entindex,omitempty"`
	SourcePlayerEntindex *int32               `protobuf:"varint,5,opt,name=source_player_entindex" json:"source_player_entindex,omitempty"`
	XXX_unrecognized     []byte               `json:"-"`
}

func (m *CDOTAUserMsg_OverheadEvent) Reset()         { *m = CDOTAUserMsg_OverheadEvent{} }
func (m *CDOTAUserMsg_OverheadEvent) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_OverheadEvent) ProtoMessage()    {}

func (m *CDOTAUserMsg_OverheadEvent) GetMessageType() DOTA_OVERHEAD_ALERT {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *CDOTAUserMsg_OverheadEvent) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *CDOTAUserMsg_OverheadEvent) GetTargetPlayerEntindex() int32 {
	if m != nil && m.TargetPlayerEntindex != nil {
		return *m.TargetPlayerEntindex
	}
	return 0
}

func (m *CDOTAUserMsg_OverheadEvent) GetTargetEntindex() int32 {
	if m != nil && m.TargetEntindex != nil {
		return *m.TargetEntindex
	}
	return 0
}

func (m *CDOTAUserMsg_OverheadEvent) GetSourcePlayerEntindex() int32 {
	if m != nil && m.SourcePlayerEntindex != nil {
		return *m.SourcePlayerEntindex
	}
	return 0
}

type CDOTAUserMsg_TutorialTipInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Progress         *int32  `protobuf:"varint,2,opt,name=progress" json:"progress,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDOTAUserMsg_TutorialTipInfo) Reset()         { *m = CDOTAUserMsg_TutorialTipInfo{} }
func (m *CDOTAUserMsg_TutorialTipInfo) String() string { return proto.CompactTextString(m) }
func (*CDOTAUserMsg_TutorialTipInfo) ProtoMessage()    {}

func (m *CDOTAUserMsg_TutorialTipInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CDOTAUserMsg_TutorialTipInfo) GetProgress() int32 {
	if m != nil && m.Progress != nil {
		return *m.Progress
	}
	return 0
}

func init() {
	proto.RegisterEnum("dota2.EDotaUserMessages", EDotaUserMessages_name, EDotaUserMessages_value)
	proto.RegisterEnum("dota2.DOTA_CHAT_MESSAGE", DOTA_CHAT_MESSAGE_name, DOTA_CHAT_MESSAGE_value)
	proto.RegisterEnum("dota2.EDotaEntityMessages", EDotaEntityMessages_name, EDotaEntityMessages_value)
	proto.RegisterEnum("dota2.DOTA_PARTICLE_MESSAGE", DOTA_PARTICLE_MESSAGE_name, DOTA_PARTICLE_MESSAGE_value)
	proto.RegisterEnum("dota2.DOTA_OVERHEAD_ALERT", DOTA_OVERHEAD_ALERT_name, DOTA_OVERHEAD_ALERT_value)
}
